FROM python:3.8.3-slim-buster

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
    apt-utils; \
    pip install --no-cache-dir pipenv; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /src

COPY src/Pipfile src/Pipfile.lock src/manage.py ./

RUN pipenv install

COPY src/djangovue ./djangovue/

CMD [ "bash", "startup.sh" ]
