version: "3.7"

services:
  postgres:
    image: postgres:11
    env_file: .env.development
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DOCKER_POSTGRES_PORT:-54432}:5432"

  django:
    image: django
    env_file: .env.development
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    volumes:
      - ./src/django:/app

  vue:
    image: vue
    env_file: .env.development
    build:
      context: .
      dockerfile: Dockerfile.vue
    ports:
      - "8080:8080"
    volumes:
      - ./src/vue:/app/frontend
      - ./src/vue/node_modules:/app/frontend/node_modules

volumes:
  pgdata:
